version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nhat
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo-data:/data/db

  server:
    image: minhnhat28/web-app-server:latest
    container_name: web-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://nhat:123456@mongo:27017/web-app?authSource=admin
    depends_on:
      - mongo

  client:
    image: minhnhat28/web-app-client:latest
    container_name: web-client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
