apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: minhnhat28/web-app-server:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://nhat:123456@mongo:27017/web-app?authSource=admin
