version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nhat
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

    # ✅ thêm healthcheck
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: web-server
    restart: always
    ports:
      - "5000:5000"

    # ✅ chỉ chạy khi mongo healthy
    depends_on:
      mongo:
        condition: service_healthy

  client:
    build: ./client
    container_name: web-client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
